server:
  port: 3000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpaex
    username: root
    password: aA!123456
  # JPA 설정
  jpa:
    properties:
      show_sql: true
      format_sql: ture
      dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddlAuto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace